### This is a script that reads Region-to-Region network data and aggregate them as a single file.

In [2]:
import pandas as pd
import json
import numpy as np
from pandas.io.json import json_normalize
from scipy.spatial.distance import cosine
import csv
import ast
import os

In [12]:
alldf = pd.DataFrame(columns=['month','day','hour','source','dest','call'])

for month in {'11','12'}:
    for day in range(1,32):        
        to_read = '../../data/CDR/region-network/ACEtoACE-2013-' + month + '-' + \
                    str(day).zfill(2) + '.csv'
        
        if os.path.isfile(to_read):
            # loading the raw data
            df = pd.read_csv(to_read) 
            df.columns = ['source','dest','hour','call']
            df['month'] = int(month)
            df['day'] = day
            
            alldf = alldf.append(df)

In [19]:
alldf = alldf[['month','day','hour','source','dest','call']]
alldf.head()

   month  day  hour  source  dest       call
0   12.0  1.0   0.0     1.0   1.0  33.130933
1   12.0  1.0   1.0     1.0   1.0  15.501586
2   12.0  1.0   2.0     1.0   1.0   8.157825
3   12.0  1.0   3.0     1.0   1.0   6.443004
4   12.0  1.0   4.0     1.0   1.0   3.293162

In [20]:
output_filename = '../../data/CDR/generated/region_network_final.csv'
alldf.to_csv(output_filename, encoding='utf-8', index=False)

In [21]:
alldf.head(30)

    month  day  hour  source  dest        call
0    12.0  1.0   0.0     1.0   1.0   33.130933
1    12.0  1.0   1.0     1.0   1.0   15.501586
2    12.0  1.0   2.0     1.0   1.0    8.157825
3    12.0  1.0   3.0     1.0   1.0    6.443004
4    12.0  1.0   4.0     1.0   1.0    3.293162
5    12.0  1.0   5.0     1.0   1.0    2.025589
6    12.0  1.0   6.0     1.0   1.0    3.761830
7    12.0  1.0   7.0     1.0   1.0    7.406733
8    12.0  1.0   8.0     1.0   1.0   11.291304
9    12.0  1.0   9.0     1.0   1.0   34.374490
10   12.0  1.0  10.0     1.0   1.0   77.452970
11   12.0  1.0  11.0     1.0   1.0  156.685623
12   12.0  1.0  12.0     1.0   1.0  196.344842
13   12.0  1.0  13.0     1.0   1.0  197.126097
14   12.0  1.0  14.0     1.0   1.0  182.336655
15   12.0  1.0  15.0     1.0   1.0  216.148969
16   12.0  1.0  16.0     1.0   1.0  276.211626
17   12.0  1.0  17.0     1.0   1.0  263.303616
18   12.0  1.0  18.0     1.0   1.0  187.700971
19   12.0  1.0  19.0     1.0   1.0  139.830757
20   12.0  1.0  20.0     1.0   1.0   70.111630
21   12.0  1.0  21.0     1.0   1.0   32.548125
22   12.0  1.0  22.0     1.0   1.0   12.959998
23   12.0  1.0  23.0     1.0   1.0   14.110463
24   12.0  1.0   0.0     1.0  10.0    4.609260
25   12.0  1.0   1.0     1.0  10.0    0.460166
26   12.0  1.0   2.0     1.0  10.0    1.338633
27   12.0  1.0   3.0     1.0  10.0    0.300401
28   12.0  1.0   4.0     1.0  10.0    0.593892
29   12.0  1.0   5.0     1.0  10.0    0.278480